# name: str
#     model_name: str
#     endpoints: default to null
#         - api_base: str
#           api_key: str
#           api_version: str optional (only for azure)
#     api_type: str
#     tokenizer: str optional (to optimize token limits)
#     parallel: int
#     system_prompt: str optional (add system instruction when generating model answer)

claude-3.5-sonnet-v2:
    model_name: claude-3.5-sonnet-v2
    endpoints:
        - api_base: http://ec2-3-19-37-251.us-east-2.compute.amazonaws.com:4000/
          api_key: tokenreplace
    api_type: openai
    parallel: 10

gpt-4o-mini:
    model_name: gpt-4o-mini
    endpoints:
        - api_base: http://ec2-3-19-37-251.us-east-2.compute.amazonaws.com:4000/
          api_key: tokenreplace
    api_type: openai
    parallel: 4

aya-expanse-8b:
    model_name: aya-expanse-8b
    endpoints:
        - api_base: http://ec2-3-19-37-251.us-east-2.compute.amazonaws.com:4000/
          api_key: tokenreplace
    api_type: openai
    parallel: 6

llama-3.1-70b:
    model_name: llama-3.1-70b
    endpoints:
        - api_base: http://ec2-3-19-37-251.us-east-2.compute.amazonaws.com:4000/
          api_key: tokenreplace
    api_type: openai
    parallel: 6

llama-3.1-8b:
    model_name: llama-3.1-8b
    endpoints:
        - api_base: http://ec2-3-19-37-251.us-east-2.compute.amazonaws.com:4000/
          api_key: tokenreplace
    api_type: openai
    parallel: 6

command-r:
    model_name: command-r
    endpoints:
        - api_base: http://ec2-3-19-37-251.us-east-2.compute.amazonaws.com:4000/
          api_key: tokenreplace
    api_type: openai
    parallel: 6

command-rplus:
    model_name: command-rplus
    endpoints:
        - api_base: http://ec2-3-19-37-251.us-east-2.compute.amazonaws.com:4000/
          api_key: tokenreplace
    api_type: openai
    parallel: 6

gemma2-9b-it:
    model_name: gemma2-9b-it
    endpoints:
        - api_base: http://ec2-3-19-37-251.us-east-2.compute.amazonaws.com:4000/
          api_key: tokenreplace
    api_type: openai
    parallel: 1

mixtral-8x7b-instruct-v0.1:
    model_name: mixtral-8x7b-instruct-v0.1
    endpoints:
        - api_base: http://ec2-3-19-37-251.us-east-2.compute.amazonaws.com:4000/
          api_key: tokenreplace
    api_type: openai
    parallel: 6

mistral-7b-instruct-v0.2:
    model_name: mistral-7b-instruct-v0.2
    endpoints:
        - api_base: http://ec2-3-19-37-251.us-east-2.compute.amazonaws.com:4000/
          api_key: tokenreplace
    api_type: openai
    parallel: 1

gpt-4o:
    model_name: gpt-4o
    endpoints: null
    api_type: openai
    parallel: 8

meltemi-instruct-7b-v1.5-orpo:
    model_name: meltemi-instruct-7b-v1.5-orpo
    endpoints:
        - api_base: http://ec2-3-19-37-251.us-east-2.compute.amazonaws.com:4000/
          api_key: tokenreplace
    api_type: openai
    parallel: 1

krikri-annealing-dpo-mixed-run1:
    model_name: krikri-annealing-dpo-mixed-run1
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: token-abc123
    api_type: openai
    parallel: 8

krikri-annealing-sft-mixed-run1:
    model_name: krikri-annealing-sft-mixed-run1
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: token-abc123
    api_type: openai
    parallel: 16

krikri-annealing-sft-stage2-run4:
    model_name: krikri-annealing-sft-stage2-run4
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: token-abc123
    api_type: openai
    parallel: 16

krikri-annealing-sft-stage2-dpo_max-run4:
    model_name: krikri-annealing-sft-stage2-dpo_max-run4
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: token-abc123
    api_type: openai
    parallel: 16

gemma-2-27b-it:
    model_name: gemma-2-27b-it
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: token-abc123
    api_type: openai
    parallel: 16

aya-expanse-32b:
    model_name: aya-expanse-32b
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: token-abc123
    api_type: openai
    parallel: 16

meltemi-annealing-sft-run5:
    model_name: meltemi-annealing-sft-run5
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: token-abc123
    api_type: openai
    parallel: 16

krikri-annealing-sft-stage2-dpo_max-epoch-1-run4:
    model_name: krikri-annealing-sft-stage2-dpo_max-epoch-1-run4
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: token-abc123
    api_type: openai
    parallel: 16
    
krikri-annealing-sft-stage2-dpo_min-epoch-1-run4:
    model_name: krikri-annealing-sft-stage2-dpo_min-epoch-1-run4
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: token-abc123
    api_type: openai
    parallel: 16

krikri-annealing-sft-stage2-dpo_min-run4:
    model_name: krikri-annealing-sft-stage2-dpo_min-run4
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: token-abc123
    api_type: openai
    parallel: 16

krikri-annealing-sft-stage2-dpo_min-length-norm-run4:
    model_name: krikri-annealing-sft-stage2-dpo_min-length-norm-run4
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: token-abc123
    api_type: openai
    parallel: 16

krikri-annealing-sft-stage2-dpo_max-length-norm-run4:
    model_name: krikri-annealing-sft-stage2-dpo_max-length-norm-run4
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: token-abc123
    api_type: openai
    parallel: 16

krikri-annealing-sft-stage2-dpo_max-length-norm-fixes_on_policy:
    model_name: krikri-annealing-sft-stage2-dpo_max-length-norm-fixes_on_policy
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: token-abc123
    api_type: openai
    parallel: 16

krikri-annealing-sft-stage2-dpo_max-length-norm-fixes_on_policy-checkpoint-1560:
    model_name: krikri-annealing-sft-stage2-dpo_max-length-norm-fixes_on_policy-checkpoint-1560
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: token-abc123
    api_type: openai
    parallel: 16

krikri-annealing-sft-stage2-dpo_max-length-norm-dpo-fixes-length-norm:
    model_name: krikri-annealing-sft-stage2-dpo_max-length-norm-dpo-fixes-length-norm
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: token-abc123
    api_type: openai
    parallel: 16
    
krikri-annealing-sft-stage2-dpo_max-length-norm-dpo-fixes_off_policy-length-norm:
    model_name: krikri-annealing-sft-stage2-dpo_max-length-norm-dpo-fixes_off_policy-length-norm
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: token-abc123
    api_type: openai
    parallel: 16

krikri-annealing-dpo-max-length-norm-dpo-fixes-length-norm-round-2:
    model_name: krikri-annealing-dpo-max-length-norm-dpo-fixes-length-norm-round-2
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: token-abc123
    api_type: openai
    parallel: 50

krikri-annealing-dpo-max-length-norm-dpo-fixes-length-norm-round-1-low-lr:
    model_name: krikri-annealing-dpo-max-length-norm-dpo-fixes-length-norm-round-1-low-lr
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: token-abc123
    api_type: openai
    parallel: 50

krikri-annealing-sft-stage2-merge-dpo-max-length-norm-dpo-fixes-length-norm_0.4-dpo_min_0.3dpo_max-length-norm-fixes_on_policy-checkpoint-1560_0.3-dare_tie:
    model_name: krikri-annealing-sft-stage2-merge-dpo-max-length-norm-dpo-fixes-length-norm_0.4-dpo_min_0.3dpo_max-length-norm-fixes_on_policy-checkpoint-1560_0.3-dare_tie
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: token-abc123
    api_type: openai
    parallel: 50

krikri-annealing-sft-stage2-merge-dpo-max-length-norm-dpo-fixes-length-norm_0.45-dpo_min_0.55-dare_tie:
    model_name: krikri-annealing-sft-stage2-merge-dpo-max-length-norm-dpo-fixes-length-norm_0.45-dpo_min_0.55-dare_tie
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: token-abc123
    api_type: openai
    parallel: 50

krikri-annealing-sft-stage2-merge-dpo-max-length-norm-dpo-fixes-length-norm_0.55-dpo_min_0.45-dare_tie:
    model_name: krikri-annealing-sft-stage2-merge-dpo-max-length-norm-dpo-fixes-length-norm_0.55-dpo_min_0.45-dare_tie
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: token-abc123
    api_type: openai
    parallel: 50

krikri-annealing-dpo-max-length-norm-dpo-fixes-length-norm-round-3-with-IF-checkpoint-2316:
    model_name: krikri-annealing-dpo-max-length-norm-dpo-fixes-length-norm-round-3-with-IF-checkpoint-2316
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: token-abc123
    api_type: openai
    parallel: 50
    
krikri-annealing-dpo-max-length-norm-dpo-fixes-length-norm-round-3-with-IF-final-checkpoint:
    model_name: krikri-annealing-dpo-max-length-norm-dpo-fixes-length-norm-round-3-with-IF-final-checkpoint
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: token-abc123
    api_type: openai
    parallel: 50